# Generated by Django 5.2.18 on 2026-10-08 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PPT', 'Permiso por protección temporal'), ('PA', 'Pasaporte')], default='CC', max_length=3)),
                ('documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('asistio', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha', 'apellidos', 'nombres'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'fecha'), name='unico_documento_por_fecha', violation_error_message='Ya existe un registro de asistencia para este documento en esa fecha.')],
            },
        ),
    ]
